FROM node:20 AS build

WORKDIR /app

COPY package.json ./

RUN rm -rf node_modules package-lock.json

RUN npm install

COPY . ./

RUN npm run build

RUN npm install -g serve

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
