version: '3.8'

services:
  # react:
  #   container_name: react_app
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - app-network
  #   depends_on:
  #     - flask
  #   restart: unless-stopped

  # flask:
  #   container_name: flask_app
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - FLASK_ENV=development
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # nginx:
  #   build: 
  #     context: ./frontend
  #   container_name: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80" 
  #   depends_on:
  #     - react
  #     - flask
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: plc
    ports:
      - "3307:3306"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge